# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uservotes',
            old_name='userr',
            new_name='user',
        ),
    ]
