# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 12:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugs', '0002_auto_20180527_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservotes',
            name='user',
        ),
        migrations.AddField(
            model_name='uservotes',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
