# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_auto_20180519_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='bug_id',
            new_name='bug',
        ),
    ]
