# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0005_remove_bug_votes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='BugComment',
        ),
        migrations.RenameModel(
            old_name='UserVotes',
            new_name='BugUserVotes',
        ),
    ]
